spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=dietiestate25_estate
    username: postgres
    password: 4886
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql

server:
  port: 8081