spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/user-api/v1/**
        - id: offer-service
          uri: lb:http://OFFER-SERVICE
          predicates:
            - Path=/offer-api/v1/offers/**

server:
  port: 8222