spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/offer?currentSchema=dietiestate25_offer
    username: postgres
    password: password1029
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql

server:
  port: 8061


application:
  config:
    user-url: http://localhost:8060/user-api/v1/users