spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: password1029
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8060
