spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user?currentSchema=dietiestate25_user
    username: postgres
    password: password1029
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql

server:
  port: 8060

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000